### ISSUE TITLE
服务（mock）返回的路由是怎么处理的

### ISSUE THREAD

**Issue by Elias-cug** [yiptsangkin/near-admin-vue#3]
查看了下代码，引入路由时有固定路由和后台返回的路由，后台返回的路由是从localStrage获取的。不明白的是，浏览器存服务返回的路由，不应该是登录成功时通过localStrage.setItem存入嘛？

**Comment by yiptsangkin** [comment]
菜单是通过接口获取的，不需要在浏览器本地存储中保留。manage.ts的router中的动态路由是标签页独立页面动态创建的。
